#source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'

  flutter_application_path = '../flutter_module'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

platform :ios, '11.0'

target 'NativeDemo' do
  install_all_flutter_pods(flutter_application_path)
  use_frameworks!
	
 # Pods for NativeDemo

end
