# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'SwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # 忽略引入库的所有警告
  inhibit_all_warnings!

  # Pods for LearnSwift

  pod 'SnapKit' # 自动布局
  pod 'Kingfisher' # 图片加载
  pod 'ESTabBarController-swift' # tabbar样式
  pod 'FSPagerView' # banner滚动图片

  pod 'Moya'
  pod 'HandyJSON'
  pod 'SwiftyJSON'

  pod 'DNSPageView' # 分页
  pod 'JXMarqueeView' # 跑马灯
  pod 'LTScrollView' # 滚动页
  pod 'MJRefresh'
  #pod 'SkeletonView'
  pod 'SwiftMessages' # 消息提示
  #pod 'YYKit'
  pod 'SVProgressHUD'
  pod 'StreamingKit' # 播放网络音频
  pod 'Alamofire' # 网络请求
  pod 'KakaJSON' # 字典转模型
  pod 'SnapKitExtend'

end
